### ISSUE TITLE
How can we add stickers on live camera preview with capture image and record video?

### ISSUE THREAD

**Issue by Vikram411** [nkmrh/FilterCam#1]
Hii @nkmrh 

After googling more than 5 hours I found your repo to record video with filters. Its really helped me to solve my problems. Now I want to add stickers to live video preview with filters. Can you help me to solve this?

**Comment by nkmrh** [comment]
Hi @Vikram411 

I'm glad that this library is useful for you. However, it seems that it will not be useful as a sticker implementation.
In implementing the sticker, I think that it is good to composite recorded videos and stickers using AVComposition or their classes.

**Comment by Vikram411** [comment]
@nkmrh  Thank you for replay.

will try to implement your suggestion.
