### ISSUE TITLE
Unable to make long videos

### ISSUE THREAD

**Issue by swakez** [nkmrh/FilterCam#14]
Firstly, your repo is just great, I guess the only ios solution which provides video recording with filter. But, at my side, the behaviour is a little unexpected. The sample app actually creates video but not of more than 4 seconds. And sometimes not even that. Can you please suggest where I am going wrong?

**Comment by nkmrh** [comment]
I checked the problem but I couldn't reproduce it. Please describe your environment.

**Comment by swakez** [comment]
The issue came unexpectedly. At times, the code worked fine. Maybe some issue with the device or any other dependency. I had to use some another lib. Thanks for the prompt reply.
