### ISSUE TITLE
Front camera having an mirror.

### ISSUE THREAD

**Issue by vishnu1989** [nkmrh/FilterCam#5]
How can I remove a mirror in front camera? I have tried in 

    private func handleVideoSampleBuffer(buffer: CMSampleBuffer) {
        filteredImage = filteredImage.transformed(by: CGAffineTransform(scaleX: 1, y: -1))}

It works without start recording. but when I start recording it just black screen record.

**Comment by nkmrh** [comment]
Hi @vishnu1989 . I think you should apply `CGAffineTransform(scaleX: -1, y: 1)` instead of `CGAffineTransform(scaleX: 1, y: -1)` and you may have to change [Composer](https://github.com/nkmrh/FilterCam/blob/master/FilterCam/Composer.swift) too. Please try it.

**Comment by RonakJani1** [comment]
how to solve front camera mirroring from the camera i also tries above method but its not working.
any other solution regarding this?

**Comment by layounisl** [comment]
this pl https://github.com/nkmrh/FilterCam/pull/6 should get the job done

**Comment by RonakJani1** [comment]
thanks buddy its worked for me!
